name: Trigger weddd Data Build
on:
  push:
    branches:
      - main
    paths:
      - 'data/weddinggo/all.json'
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WEDDINGGO_PAT_TOKEN }}
          repository: ablokr/wedding-html
          event-type: api_data_updated
